server {
    listen 80;
    listen [::]:80;
    server_name controla.SEU-DOMINIO.com;

    # o mesmo limite do post_max_size do deploy/php.ini
    client_max_body_size 16m;

    location / {
        # o proxy.wan do config.ini
        proxy_pass http://127.0.0.1:8081;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
