; php.ini do container. Quem decide se o erro aparece na tela e o `enviroment`
; do config.ini;

expose_php = Off
display_errors = Off
display_startup_errors = Off
log_errors = On

error_log = /proc/self/fd/2

memory_limit = 256M
max_execution_time = 60
post_max_size = 16M
upload_max_filesize = 16M

date.timezone = America/Sao_Paulo
default_charset = UTF-8

opcache.enable = 1
opcache.memory_consumption = 128
opcache.max_accelerated_files = 10000

opcache.validate_timestamps = 0

session.cookie_httponly = 1
session.cookie_samesite = Lax

session.use_strict_mode = 1

session.cookie_lifetime = 2592000
session.gc_maxlifetime = 2592000

; ligar quando o host.<location> for https
; session.cookie_secure = 1
